version: "3.8"

services:
  otel-dotnet6-todo-app:
    build:
      context: ..
      dockerfile: tilt/Dockerfile
    volumes:
      - ..:/workspace:cached
      - ../scripts/db:/docker-entrypoint-initdb.d:ro
    command: dotnet watch run --project /workspace/src/Api/Api.csproj
    ports:
      - "5001:5001"
    network_mode: service:db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_CONNECTION=Host=localhost;Database=tododb;Username=postgres;Password=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
    depends_on:
      - db
      - jaeger

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../scripts/db:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  jaeger:
    image: jaegertracing/all-in-one:latest
    network_mode: service:db
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP

volumes:
  postgres-data:
