# Prometheus設定ファイル
global:
  scrape_interval: 5s     # メトリクス収集の間隔

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otelcol:8889']
    metrics_path: '/metrics'

  - job_name: 'todo-api'
    static_configs:
      - targets: ['todo-api:5000']
    metrics_path: '/metrics/prometheus'
    scheme: 'http'
